# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81cb361d8695f81231f7eee86adb3e5ac47b2307f229acc871866ca7e3ccaa003a9b012213809b0d5640501e9c69a6d369cade048b589de441d705bf68be8ac8

test:
  secret_key_base: 5e21a750d1a596d50fb2093193d74abe756d99b85ee28c0b028111dc5e778287a375f8977aede22a3baf8226134aee935102302f73c22c62d890b83a4509b1dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
