# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44d13b4ad0d479705dc9dfe047fb14eec46c924e21a48ae073dedf2c8c85c8ba938111c63986beb235d041f6526747c9cb0faeaab46d00f05a5bdc036f2d20c9

test:
  secret_key_base: 9eaef66508b90366e92c130db6e10e1398b6eaf5300178e12a62f7ac6e82ddc3d48440de1210bdeb79deb75ba8c9bcfb975c863224dd98c4b7eb0749e2a9089c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
